### ISSUE TITLE
Cannot create a polygon with unclosed exterior

### ISSUE THREAD

**Issue by snowmanirl** [azavea/geotrellis-collections-api-research#16]
Caused by: java.lang.RuntimeException: Cannot create a polygon with unclosed exterior: LINESTRING 
(20037508.342789244 �, 20037508.342789244 8531882.764988864,  ...........   20037508.342789244 �, 20037508.342789244 �, 20037508.342789244 �)
Like I found a bug here. (https://github.com/azavea/geotrellis-collections-api-research/blob/0392fb11f4c1364c2680e18b33617cf9103c1e27/ingest/src/main/scala/LandCoverPaint.scala#L84 )
Also tried through docker and idea,both failed.
Is there some way to avoid this?Like I'm missing sth.

**Comment by snowmanirl** [comment]
I've fixed it.The tiff download link in the docs is incorrect and the link in the makefile is correct.

**Comment by kellyi** [comment]
Thanks for reporting this -- and glad you were able to figure it out!

The geotiff link in the README goes to the original source for the data (which requires clicking through and unzipping a file) but we just put the tif itself on s3 for use in the Makefile.
